name: Publish VSCode Extension

description: "Builds the .vsix package and uploads it to the GitHub release for the given tag."

inputs:
  tag:
    description: "The release tag to use for the upload (e.g., tts-code@v1.1.0)"
    required: true
  token:
    description: "GitHub token for authentication"
    required: false
    default: ${{ github.token }}

outputs:
  upload_url:
    description: "The upload URL used for the release asset."
    value: ${{ steps.get_release.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.14

    - name: Build and Upload VSIX using script
      shell: bash
      run: .github/actions/publish-extension/upload.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_IDENTIFIER: ${{ matrix.release.tag }}
        TARGET_FOLDER: .

    - name: Report Status
      shell: bash
      run: |
        echo "Published extension: ${{ steps.build_vsix.outputs.vsix_name }}" >> $GITHUB_STEP_SUMMARY