name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Composite NPM Test Action
        uses: ./.github/actions/npm-test
        with:
          path: .
          name: lekman-tts-code
          token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 22.14.0
          build: true
          test: true
          audit: true
          coverage: ${{ github.event_name == 'pull_request' }}
