name: Continuous Integration

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main, master]

permissions:
  contents: write
  pull-requests: write
  packages: write
  actions: write
  checks: write
  security-events: write

jobs:
  test:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run checks
        uses: ./.github/actions/npm-test
        with:
          path: .
          name: tts-code
          token: ${{ secrets.GITHUB_TOKEN }}
          coverage: true # ${{ github.event_name == 'pull_request' }}

      - name: Upload coverage and test results to Codecov
        uses: ./.github/actions/coverage
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          coverage_files: ${{ steps.npm-test.outputs.coverage }}
          test_report_files: ${{ steps.npm-test.outputs.junit }}
